name       : gutenprint
version    : 5.2.11
release    : 2
source     :
    - http://downloads.sourceforge.net/gimp-print/gutenprint-5.2.11.tar.bz2 : c1a34cd2e02527de4d2a9bf6c14732cb9aa11b333f771eb6043fdc974de24df9
license    : GPL-2.0
summary    : Many printer drivers
description: |
    The Gutenprint (formerly Gimp-Print) package contains high quality drivers for many brands and models of printers 
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(gtk+-2.0)
    - cups-devel
setup      : |
    %configure --disable-static --disable-static-genppd --enable-cups-ppds --enable-simplified-cups-ppds=only --enable-translated-cups-ppds --enable-globalized-cups-ppds
build      : |
    %make
install    : |
    %make_install
