name       : gutenprint
version    : 5.2.10
release    : 1
source     :
    - http://downloads.sourceforge.net/gimp-print/gutenprint-5.2.10.tar.bz2 : 431f352b412dfb9809d126a85a37a1fcd1c1826275ace8cdcd4fd9a6ee360e59
license    : GPL-2.0
summary    : Many printer drivers
description: |
    The Gutenprint (formerly Gimp-Print) package contains high quality drivers for many brands and models of printers 
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
