name       : gutenprint
version    : 5.3.1
release    : 7
source     :
    - https://sourceforge.net/projects/gimp-print/files/gutenprint-5.3/5.3.1/gutenprint-5.3.1.tar.xz/download : d80d8f5272d15bca5710f6ef4a2bb95e76d34e1155c5bcd5e83cb9f0a111d0d4
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Many printer drivers
description: |
    The Gutenprint (formerly Gimp-Print) package contains high quality drivers for many brands and models of printers
builddeps  :
    - pkgconfig(libusb-1.0)
    - cups-devel
setup      : |
    %configure --disable-static \
        --disable-static-genppd \
        --enable-cups-ppds \
        --enable-simplified-cups-ppds=only \
        --enable-translated-cups-ppds \
        --enable-globalized-cups-ppds
build      : |
    %make
install    : |
    %make_install
