name       : gutenprint
version    : 5.2.12
release    : 3
source     :
    - http://downloads.sourceforge.net/gimp-print/gutenprint-5.2.12.tar.bz2 : a42489fd7d6f2e4320811754bb80b0cd845db6632b52f819fbc2b4b75057341b
license    : GPL-2.0
component  : desktop.core
summary    : Many printer drivers
description: The Gutenprint (formerly Gimp-Print) package contains high quality drivers for many brands and models of printers
builddeps  :
    - pkgconfig(libusb-1.0)
    - cups-devel
setup      : |
    %configure --disable-static \
        --disable-static-genppd \
        --enable-cups-ppds \
        --enable-simplified-cups-ppds=only \
        --enable-translated-cups-ppds \
        --enable-globalized-cups-ppds
build      : |
    %make
install    : |
    %make_install
